### ISSUE TITLE
Set min brightness

### ISSUE THREAD

**Issue by benwtks** [Ventto/lux#3]
Can't set minimum brightness "lux -m 50" doesn't work

```
$ lux -m 50
Usage: lux [OPTION]...
Brightness option values are positive integers.
Percent mode, add "%" after values (operation options only).

Without option, it prints controller name and brightness info:
{controller} {min;value;max}

Information:
  -h:  Prints this help and exits
  -v:  Prints version info and exists

Thresholds (can be used in conjunction):
  -m:  Set the brightness min (min < max)
  -M:  Set the brightness max (max > min)

Operations (with percent mode):
  -a:  Add value
  -s:  Subtract value
  -S:  Set the brightness value (set thresholds will be ignored)

Controllers:
  -c:  Set the controller to use (needs argument).
       Use any controller name in /sys/class/backlight as argument.
       Otherwise a controller is automatically chosen (default).
```

**Comment by jamesooo** [comment]
from what i can tell by reading the code the min and max options only apply to the current operation and the help menu will appear any time you don't provide the script with a new value (or percent) to set the interface to. it seems to me like this was intended to be used by some behind the scenes logic (setting brightness by keypress) rather than ad-hoc.

**Comment by Ventto** [comment]
Hi @benwtks,
Thanks for the feedback.

@jamesooo is right. 

`-m, -M` are threshold options and meant to be used in conjunction with operation options which set a new brighness value (raw or percent one). 

Feel free to propose some fixes to the help menu to make it more understandable or some changes to option logic.

**Comment by Ventto** [comment]
@benwtks,
I've fixed the usage.
Thanks for contribution.
